"""empty message

Revision ID: 0955bb8ee998
Revises: d243d0613a0f
Create Date: 2023-09-18 14:38:31.491788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0955bb8ee998'
down_revision: Union[str, None] = 'd243d0613a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ML_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ML_model_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ML_model')),
    sa.UniqueConstraint('model_path', name=op.f('uq_ML_model_model_path'))
    )
    op.drop_table('model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('model_path', sa.VARCHAR(), nullable=False),
    sa.Column('model_pubkey', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_model'),
    sa.UniqueConstraint('model_name', name='uq_model_model_name')
    )
    op.drop_table('ML_model')
    # ### end Alembic commands ###
