"""empty message

Revision ID: 8b2f72e9c819
Revises: 5b81c61d9e7a
Create Date: 2023-09-18 14:54:30.075017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2f72e9c819'
down_revision: Union[str, None] = '5b81c61d9e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ML_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ML_model_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('ML_model_path', sa.String(), nullable=False))
        batch_op.drop_constraint('uq_ML_model_model_path', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_ML_model_ML_model_path'), ['ML_model_path'])
        batch_op.drop_column('model_name')
        batch_op.drop_column('model_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ML_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_path', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('model_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_ML_model_ML_model_path'), type_='unique')
        batch_op.create_unique_constraint('uq_ML_model_model_path', ['model_path'])
        batch_op.drop_column('ML_model_path')
        batch_op.drop_column('ML_model_name')

    # ### end Alembic commands ###
